import flowbitePlugin from 'flowbite/plugin';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    'node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  safelist: [
    'w-64',
    'w-1/2',
    'rounded-l-lg',
    'rounded-r-lg',
    'bg-gray-200',
    'grid-cols-4',
    'grid-cols-7',
    'h-6',
    'leading-6',
    'h-9',
    'leading-9',
    'shadow-lg',
    'bg-opacity-50',
    'dark:bg-opacity-80',
  ],
  theme: {
    extend: {
      screens: {
        xs: '480px',
      },
      colors: {
        primary: '#0079B7',
        secondary: '#E84E1B',
        success: '#07C600',
        info: '#005F90',
        warning: '#DC8400',
        danger: '#E90404',
        dark: '#707070',
        light: '#DCEBF4',

        orange: '#DC8400',
        green: '#07C600',
        black: '#040404',
        red: {
          1: '#E90404',
          2: '#FDE5E5',
        },
        beige: {
          1: '#F8EAD6',
          2: '#FCF3E8',
        },
        blue: {
          1: '#005F90',
          2: '#5EAAD1',
          3: '#D4E8F3',
          4: '#DCEBF4',
          5: '#E9F1F5',
          'calm-waters': '#E4F2F9',
        },
        gray: {
          1: '#BCBCBC',
          2: '#CDCDCD',
          3: '#CECECE',
          dark: {
            1: '#707070',
            2: '#949494',
            3: '#A6A6A6',
          },
          bright: {
            DEFAULT: '#E5EFF4',
            1: '#E9E9E9',
            2: '#F3F3F3',
            3: '#E5E5E5',
          },
          light: {
            1: '#DADADA',
            2: '#DBDBDB',
            3: '#E3E3E3',
            4: '#E5E5E5',
          },
        },
      },
      fontFamily: {
        sans: [
          'Tajawal',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        body: [
          'Tajawal',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      transitionProperty: {
        width: 'width',
      },
      textDecoration: ['active'],
      minWidth: {
        kanban: '28rem',
      },
    },
  },

  plugins: [flowbitePlugin],
};
