name: Continuous Integration-Delivery

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch .env from s3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://shefaa-${{ github.ref_name }}-admin-dashboard-env/
          destination: .
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          flags: --recursive

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-image-on-vps:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: ${{ github.ref_name }}
    # Only run this job on the "prod" branch
    if: github.ref_name == 'prod'
    steps:
      - name: Deploy in VPS
        env:
          PRIVATE_KEY: ${{ secrets.VPS_PRIV  }}
          HOSTNAME: ${{ secrets.VPS_HOST  }}
          USER_NAME: ${{ secrets.VPS_USER  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            chmod +x /home/admin/shefaa/shefaa-backend-compose/scripts/deploy_service.sh &&
            /home/admin/shefaa/shefaa-backend-compose/scripts/deploy_service.sh shefaa_${{ github.event.repository.name }} ghcr.io/spiritude/${{ github.event.repository.name }}:${{github.ref_name}}
          '
